services:
  - type: web
    name: gaokao-volunteer
    env: python
    region: singapore
    plan: free
    buildCommand: pip3 install -r requirements.txt
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
